---
name: Build protoc
run-name: Build protoc

on:
  push:
  workflow_call:

jobs:
  protoc:
    runs-on: ubuntu-latest
    concurrency:
      # ensure protoc is built first
      group: ${{ github.run_id }}
    permissions:
      packages: write
      contents: write
    strategy:
      matrix:
        image:
          - protoc
          - protoc-cpp
          - protoc-go
          - protoc-java
          - protoc-node
          - protoc-swift
          - protoc-web
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: ./publish.sh
        env:
          RELEASE_TAG: ${{ github.ref_name == github.event.repository.default_branch }}
          IMAGE: ${{ matrix.image }}
