# yamllint disable rule:line-length
---
name: Build protoc

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Create release tag'
        required: false
        type: boolean

jobs:
  protoc:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish
        env:
          RELEASE_TAG: ${{ github.event.inputs.release_tag }}
        run: ./publish.sh
