# yamllint disable rule:line-length
---
name: Build protoc
run-name: Build ${{ github.event.inputs.image }} with release tag ${{ github.event.inputs.release_tag }}

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      image:
        type: choice
        description: Image
        required: true
        default: 'protoc'
        options:
          - protoc
          - protoc-cpp
          - protoc-go
          - protoc-java
          - protoc-node
          - protoc-swift
          - protoc-web
      release_tag:
        description: 'Create release tag'
        required: false
        type: boolean

jobs:
  protoc:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish
        env:
          RELEASE_TAG: ${{ github.event.inputs.release_tag }}
          IMAGE: ${{ github.event.inputs.image }}
        run: ./publish.sh
